spring.application.name=academia

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=bWluaGEtY2hhdmUtc2VjcmV0YS1zdXBlci1zZWd1cmEtcXVlLWRldmUtdGVyLXBlbG8tbWVub3MtMjU2LWJpdHMtb2s=
jwt.expiration=86400000
